### ISSUE TITLE
Windows unable to find 'SpotifyPlayerControl.exe' within CMD and SAMMI

### ISSUE THREAD

**Issue by WittyBanter** [dichternebel/spotify-player-control-cli#1]

**Comment by dichternebel** [comment]
Hi!

I see that you closed the issue already. Did you manage to get it working?

Basically there is no registration of the application to the system. So 
you have to provide the path information in SAMMI or be in the same 
folder like the application to call if from cmd.
Hopefully, you got it working.
If not, feel free to contact me on Discord directly.

Am 12.01.2023 um 06:59 schrieb WittyBanter:

**Comment by WittyBanter** [comment]
I did, just closed it to save you the hassle. (and because i felt a little silly after i figured it out...)

Thank you for the tool!
